import {
  AllocatorAuditOutcome,
  AllocatorAuditStatesData,
} from '../types.allocator';

export const edition5AllocatorAuditStatesData: AllocatorAuditStatesData[] = [
  {
    allocatorId: 'f03019833',
    allocatorName: 'Bewell Technology Limited',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.failed,
        datacap_amount: 0,
      },
    ],
  },
  {
    allocatorId: 'f03011062',
    allocatorName: 'Origin Storage',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.failed,
        datacap_amount: 0,
      },
    ],
  },
  {
    allocatorId: 'f03012749',
    allocatorName: 'Tianji Studio Fil+',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
    ],
  },
  {
    allocatorId: 'f03018491',
    allocatorName: '1475 EFil+',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.failed,
        datacap_amount: 0,
      },
    ],
  },
  {
    allocatorId: 'f03019858',
    allocatorName: 'Antalpha',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 2.5,
      },
    ],
  },
  {
    allocatorId: 'f03019913',
    allocatorName: 'Big Frog DAYOU',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.failed,
        datacap_amount: 0,
      },
    ],
  },
  {
    allocatorId: 'f03019835',
    allocatorName: 'CloudX-Lab',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.failed,
        datacap_amount: 0,
      },
    ],
  },
  {
    allocatorId: 'f03014490',
    allocatorName: 'EF',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
    ],
  },
  {
    allocatorId: 'f03013312',
    allocatorName: 'Filwallet',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
    ],
  },
  {
    allocatorId: 'f03011025',
    allocatorName: 'LendMi',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
    ],
  },
  {
    allocatorId: 'f03014641',
    allocatorName: 'MetaEra',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.unknown,
        datacap_amount: 0.5,
      },
    ],
  },
  {
    allocatorId: 'f03019839',
    allocatorName: 'Pluskit',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 2.5,
      },
    ],
  },
  {
    allocatorId: 'f03014594',
    allocatorName: 'RFfil',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
    ],
  },
  {
    allocatorId: 'f03019863',
    allocatorName: 'VSTAR',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
    ],
  },
  {
    allocatorId: 'f03014781',
    allocatorName: 'BitEngine Reeta',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
    ],
  },
  {
    allocatorId: 'f03019261',
    allocatorName: 'ByteBase (Destore)',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 10,
      },
    ],
  },
  {
    allocatorId: 'f03018489',
    allocatorName: 'Caro',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
    ],
  },
  {
    allocatorId: 'f03019850',
    allocatorName: 'Filedrive',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
    ],
  },
  {
    allocatorId: 'f03019853',
    allocatorName: 'FilscanOfficial',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
    ],
  },
  {
    allocatorId: 'f03019845',
    allocatorName: 'Genesis',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 2.5,
      },
    ],
  },
  {
    allocatorId: 'f03014732',
    allocatorName: 'Hash Team',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
    ],
  },
  {
    allocatorId: 'f03019942',
    allocatorName: 'IPFSCN',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
    ],
  },
  {
    allocatorId: 'f03012911',
    allocatorName: 'Marshall ',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 5,
      },
    ],
  },
  {
    allocatorId: 'f03019924',
    allocatorName: 'NewHuoPool',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
    ],
  },
  {
    allocatorId: 'f03018029',
    allocatorName: 'Non Entropy',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
    ],
  },
  {
    allocatorId: 'f03014608',
    allocatorName: 'QC Data Center',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
    ],
  },
  {
    allocatorId: 'f03019931',
    allocatorName: 'TopBlocks',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 2.5,
      },
    ],
  },
  {
    allocatorId: 'f03019831',
    allocatorName: 'Venus',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
    ],
  },
  {
    allocatorId: 'f03014659',
    allocatorName: 'ZCFIL+',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
    ],
  },
  {
    allocatorId: 'f03018530',
    allocatorName: 'ZetaCube',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
    ],
  },
  {
    allocatorId: 'f03016877',
    allocatorName: 'Blockchain World FIL+ DC',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
    ],
  },
  {
    allocatorId: 'f03018494',
    allocatorName: 'DCENT - NC Allocator',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 10,
      },
    ],
  },
  {
    allocatorId: 'f03010575',
    allocatorName: 'DSPA',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
    ],
  },
  {
    allocatorId: 'f03015751',
    allocatorName: 'FIDL Open',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
    ],
  },
  {
    allocatorId: 'f03010601',
    allocatorName: 'GreaterHeat',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
    ],
  },
  {
    allocatorId: 'f03011612',
    allocatorName: 'IPFSTT ',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 10,
      },
    ],
  },
  {
    allocatorId: 'f02849382',
    allocatorName: 'Kernelogic (KFDA)',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
    ],
  },
  {
    allocatorId: 'f03012494',
    allocatorName: 'Storify Data Fortress',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 10,
      },
    ],
  },
  {
    allocatorId: 'f03010963',
    allocatorName: 'SXXFuture',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 5,
      },
    ],
  },
  {
    allocatorId: 'f03004870',
    allocatorName: 'TOP POOL',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.unknown,
        datacap_amount: 0.5,
      },
    ],
  },
  {
    allocatorId: 'f03019298',
    allocatorName: 'CIDgravity decentralized onboarding to self-selected SPs',
    audits: [],
  },
  {
    allocatorId: 'f03018562',
    allocatorName: 'Dataswap',
    audits: [],
  },
  {
    allocatorId: 'f03018475',
    allocatorName: 'DCENT Fil+',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
    ],
  },
  {
    allocatorId: 'f03019926',
    allocatorName: 'Max',
    audits: [],
  },
  {
    allocatorId: 'f03019939',
    allocatorName: 'Nandit Mehra',
    audits: [],
  },
  {
    allocatorId: 'f03019861',
    allocatorName: 'Nebula Block',
    audits: [],
  },
  {
    allocatorId: 'f03015081',
    allocatorName: 'New Web Group (E-Fil+)',
    audits: [],
  },
  {
    allocatorId: 'f03019935',
    allocatorName: 'Patapon',
    audits: [],
  },
  {
    allocatorId: 'f03019912',
    allocatorName: 'PiKNiK FIL+',
    audits: [],
  },
  {
    allocatorId: 'f03019866',
    allocatorName: '(StorSwift) Manual',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.unknown,
        datacap_amount: 0.5,
      },
    ],
  },
  {
    allocatorId: 'f03019944',
    allocatorName: 'ANTPOOL Pathway',
    audits: [],
  },
  {
    allocatorId: 'f03019865',
    allocatorName: 'Bitmain USA',
    audits: [],
  },
  {
    allocatorId: 'f02824311',
    allocatorName: 'CIDgravity data preparation and onboarding',
    audits: [],
  },
  {
    allocatorId: 'f03019296',
    allocatorName: 'CIDgravity decentralized onboarding to the mix',
    audits: [],
  },
  {
    allocatorId: 'f02903211',
    allocatorName: 'EasyOnboard Allocator',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.failed,
        datacap_amount: 0,
      },
    ],
  },
  {
    allocatorId: 'f02943486',
    allocatorName: 'FF Social Impact',
    audits: [],
  },
  {
    allocatorId: 'f03019836',
    allocatorName: 'FrogHub',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.unknown,
        datacap_amount: 0.5,
      },
    ],
  },
  {
    allocatorId: 'f03019859',
    allocatorName: 'Herony',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
    ],
  },
  {
    allocatorId: 'f03024159',
    allocatorName: 'METAVERSEDATAMINING',
    audits: [],
  },
  {
    allocatorId: 'f03013315',
    allocatorName: 'STCloud',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
    ],
  },
  {
    allocatorId: 'f03019840',
    allocatorName: 'Waterdrop Lab',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.failed,
        datacap_amount: 0,
      },
    ],
  },
  {
    allocatorId: 'f03019927',
    allocatorName: 'Max',
    audits: [],
  },
  {
    allocatorId: 'f03018314',
    allocatorName: 'Niwan Dao',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.failed,
        datacap_amount: 0,
      },
    ],
  },
  {
    allocatorId: 'f03011057',
    allocatorName: 'Top Value',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.failed,
        datacap_amount: 0,
      },
    ],
  },
  {
    allocatorId: 'f02871322',
    allocatorName: 'Ehume',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
    ],
  },
  {
    allocatorId: 'f03018484',
    allocatorName: 'BDX',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.failed,
        datacap_amount: 0,
      },
    ],
  },
  {
    allocatorId: 'f03012741',
    allocatorName: 'ND Cloud (ND Labs)',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.unknown,
        datacap_amount: 0.5,
      },
    ],
  },
  {
    allocatorId: 'f03019921',
    allocatorName: 'Open Gate',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 2.5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.unknown,
        datacap_amount: 0.5,
      },
    ],
  },
  {
    allocatorId: 'f03019856',
    allocatorName: 'IPFS Force',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passedConditionally,
        datacap_amount: 2.5,
      },
    ],
  },
  {
    allocatorId: 'f03012747',
    allocatorName: 'ND Labs Enterprise',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
    ],
  },
  {
    allocatorId: 'f03015757',
    allocatorName: 'FIDL Enterprise',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 10,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 20,
      },
    ],
  },
  {
    allocatorId: 'f03019950',
    allocatorName: 'Deep Kapur',
    audits: [],
  },
  {
    allocatorId: 'f03019948',
    allocatorName: 'Power Meta Corp',
    audits: [],
  },
  {
    allocatorId: 'f03018026',
    allocatorName: 'RRM Global',
    audits: [],
  },
  {
    allocatorId: 'f03019909',
    allocatorName: 'Starlight (Enterprise Data Management System)',
    audits: [],
  },
  {
    allocatorId: 'f03018977',
    allocatorName: 'Titan Network',
    audits: [],
  },
  {
    allocatorId: 'f03019928',
    allocatorName: 'web3mine AG',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.passed,
        datacap_amount: 5,
      },
    ],
  },
  {
    allocatorId: 'f03019938',
    allocatorName: 'XnMatrix',
    audits: [],
  },
  {
    allocatorId: 'f03017718',
    allocatorName: 'DeStor',
    audits: [],
  },
  {
    allocatorId: 'f03019934',
    allocatorName: 'FBG Allocator',
    audits: [],
  },
  {
    allocatorId: 'f03019847',
    allocatorName: 'Guazi Dynamic/Fatman',
    audits: [
      {
        started: null,
        ended: null,
        dc_allocated: null,
        outcome: AllocatorAuditOutcome.failed,
        datacap_amount: 0,
      },
    ],
  },
];
