-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "AllocatorReportCheck" ADD VALUE 'STORAGE_PROVIDER_DISTRIBUTION_ALL_LOCATED_IN_THE_SAME_REGION';
ALTER TYPE "AllocatorReportCheck" ADD VALUE 'STORAGE_PROVIDER_DISTRIBUTION_PROVIDERS_EXCEED_PROVIDER_DEAL';
ALTER TYPE "AllocatorReportCheck" ADD VALUE 'STORAGE_PROVIDER_DISTRIBUTION_PROVIDERS_EXCEED_MAX_DUPLICATION';
ALTER TYPE "AllocatorReportCheck" ADD VALUE 'STORAGE_PROVIDER_DISTRIBUTION_PROVIDERS_UNKNOWN_LOCATION';
ALTER TYPE "AllocatorReportCheck" ADD VALUE 'STORAGE_PROVIDER_DISTRIBUTION_PROVIDERS_RETRIEVABILITY_ZERO';
ALTER TYPE "AllocatorReportCheck" ADD VALUE 'STORAGE_PROVIDER_DISTRIBUTION_PROVIDERS_RETRIEVABILITY_75';
ALTER TYPE "AllocatorReportCheck" ADD VALUE 'STORAGE_PROVIDER_DISTRIBUTION_PROVIDERS_IPNI_MISREPORTING';
ALTER TYPE "AllocatorReportCheck" ADD VALUE 'STORAGE_PROVIDER_DISTRIBUTION_PROVIDERS_IPNI_NOT_REPORTING';
ALTER TYPE "AllocatorReportCheck" ADD VALUE 'STORAGE_PROVIDER_DISTRIBUTION_PROVIDERS_DECLARED_NOT_USED';
ALTER TYPE "AllocatorReportCheck" ADD VALUE 'STORAGE_PROVIDER_DISTRIBUTION_PROVIDERS_NOT_DECLARED';
ALTER TYPE "AllocatorReportCheck" ADD VALUE 'DEAL_DATA_REPLICATION_LOW_REPLICA';
ALTER TYPE "AllocatorReportCheck" ADD VALUE 'DEAL_DATA_REPLICATION_HIGH_REPLICA';
ALTER TYPE "AllocatorReportCheck" ADD VALUE 'DEAL_DATA_REPLICATION_CID_SHARING';
ALTER TYPE "AllocatorReportCheck" ADD VALUE 'MULTIPLE_ALLOCATORS';
ALTER TYPE "AllocatorReportCheck" ADD VALUE 'NOT_ENOUGH_COPIES';
ALTER TYPE "AllocatorReportCheck" ADD VALUE 'INACTIVITY';
ALTER TYPE "AllocatorReportCheck" ADD VALUE 'UNIQ_DATA_SET_SIZE_TO_DECLARED';
