/*
  Warnings:

  - The values [STORAGE_PROVIDER_DISTRIBUTION_HEALTHY,STORAGE_PROVIDER_DISTRIBUTION_PROVIDERS_IN_THE_SAME_REGION] on the enum `ClientReportCheck` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ClientReportCheck_new" AS ENUM ('STORAGE_PROVIDER_DISTRIBUTION_ALL_LOCATED_IN_THE_SAME_REGION', 'STORAGE_PROVIDER_DISTRIBUTION_PROVIDERS_EXCEED_PROVIDER_DEAL', 'STORAGE_PROVIDER_DISTRIBUTION_PROVIDERS_EXCEED_MAX_DUPLICATION', 'STORAGE_PROVIDER_DISTRIBUTION_PROVIDERS_UNKNOWN_LOCATION', 'STORAGE_PROVIDER_DISTRIBUTION_PROVIDERS_RETRIEVABILITY_ZERO', 'STORAGE_PROVIDER_DISTRIBUTION_PROVIDERS_RETRIEVABILITY_75');
ALTER TABLE "client_report_check_result" ALTER COLUMN "check" TYPE "ClientReportCheck_new" USING ("check"::text::"ClientReportCheck_new");
ALTER TYPE "ClientReportCheck" RENAME TO "ClientReportCheck_old";
ALTER TYPE "ClientReportCheck_new" RENAME TO "ClientReportCheck";
DROP TYPE "ClientReportCheck_old";
COMMIT;
