name: Check types and SQL
on:
  workflow_call:

jobs:
  build-db:
    runs-on: ubuntu-latest
    services:
        postgres:
          image: postgres
          env:
            POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432
        postgresDmob:
          image: postgres
          env:
            POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5433:5432
    env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres?connection_limit=50
        DMOB_DATABASE_URL: postgres://postgres:postgres@localhost:5433/postgres
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install prisma
        run: npm install prisma@latest

      - name: Init tmp db
        run: npx prisma migrate reset --force --schema=./prisma/schema.prisma

      - name: Init dmob-like tmp db
        run: psql $DMOB_DATABASE_URL < ./ci/dmob-mock-db.sql
    
      - name: Build
        env:
            DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/postgres?connection_limit=50
            DMOB_DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5433/postgres
        run: docker build --secret id=DATABASE_URL --secret id=DMOB_DATABASE_URL . --add-host=host.docker.internal:host-gateway

