name: Check linter, formatting, tests

on:
  workflow_call:

jobs:
  format_and_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Code format
        run: npm run format

      - name: Lint code
        run: npm run lint
